apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-validator
  labels:
    app: compliance-validator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compliance-validator
  template:
    metadata:
      labels:
        app: compliance-validator
    spec:
      containers:
      - name: compliance-validator
        image: fahimr97/compliance-validator:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-validator
  labels:
    app: compliance-validator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: compliance-validator
